### ISSUE TITLE
Feature: `format` as json.Options

### ISSUE THREAD

**Issue by morlay** [go-json-experiment/json#52] opened 2024-10-10 02:26 UTC
may marshal or unmarshal value directly, not just in struct

```go
json.Marshal([]byte("11111"), json.Format("hex"))
```

**Comment by dsnet** [comment] 2024-10-18 04:11
We considered making format a first class option, but there are gnarly questions about whether it only applies to the next top-level value or recursively across the entire tree.

**Comment by morlay** [comment] 2024-10-19 07:07
> We considered making format a first class option, but there are gnarly questions about whether it only applies to the next top-level value or recursively across the entire tree.

no idea. 
in fact, i prefer to use `encoding.Text*arshaler` instead. 

I'm implementing json unmarshal with custom validating base on go-json-experiment. 
here is no way to pass `format` option in my tree walk.
https://github.com/octohelm/courier/blob/main/pkg/validator/internal/value.go#L560

example: https://github.com/octohelm/courier/blob/main/pkg/validator/arshal_test.go

**Comment by dsnet** [comment] 2024-11-20 00:52
Closing as duplicate of #46.

**Closed by dsnet** 2024-11-20 00:52 UTC

**Comment by dsnet** [comment] 2025-01-29 21:20
You may be interested in https://github.com/go-json-experiment/json/pull/138. We're not currently planning on adding this to the initial release of v2, but it is worth filing as a follow-up proposal.
